# Generated by Django 4.1.1 on 2022-10-18 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_translate_alter_explain_explain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translate',
            name='language_from',
        ),
        migrations.RemoveField(
            model_name='translate',
            name='language_to',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.language'),
        ),
    ]
