# Generated by Django 4.1.1 on 2022-10-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_translate_language_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translate',
            name='first_language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='translate',
            name='second_language',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
